from enum import Enum
from .constants import (
    REMEMBER_TEXT, UNDERSTAND_TEXT, APPLY_TEXT,ANALYZE_TEXT,
    EVALUATE_TEXT, CREATE_TEXT, FACTUAL_KNOWLEDGE_TEXT,CONCEPTUAL_KNOWLEDGE_TEXT,
    PROCEDURAL_KNOWLEDGE_TEXT, BLOOM_TABLE_TEXT, BLOOM_DIFFICULTY_CLARIFICATION_TEXT,USEFUL_DIMENSIONS_OF_BLOOMPERLEVEL_DIFFICULTY,
    REMEMBER_DIFFICULTY_TEXT,UNDERSTAND_DIFFICULTY_TEXT, METACOGNITIVE_KNOWLEDGE_TEXT,APPLY_DIFFICULTY_TEXT,ANALYZE_DIFFICULTY_TEXT,
    EVALUATE_DIFFICULTY_TEXT,CREATE_DIFFICULTY_TEXT
)


class QuestionDifficulty(Enum):
    z = "multiple_choice"
    TRUE_FALSE = "true_false"


# ----- (Each complexlity dimension)
BLOOM_FRAMEWORK_TEXT = BLOOM_TABLE_TEXT + BLOOM_DIFFICULTY_CLARIFICATION_TEXT
# Bloom's taxonomy (cognitive dimension)
class CognitiveComplexity(Enum):
    REMEMBER=(1,REMEMBER_TEXT)
    UNDERSTAND=(2,UNDERSTAND_TEXT)
    APPLY=(3,APPLY_TEXT)
    ANALYZE=(4,ANALYZE_TEXT)
    EVALUATE=(5,EVALUATE_TEXT)
    CREATE=(6,CREATE_TEXT)

# Bloom's taxonomy (Knowledge Dimension) 
class KnowlegeComplexity(Enum):
    FACTUAL_KNOWLEDGE=(1,FACTUAL_KNOWLEDGE_TEXT)
    CONCEPTUAL_KNOWLEDGE=(2,CONCEPTUAL_KNOWLEDGE_TEXT)
    PROCEDURAL_KNOWLEDGE=(3,PROCEDURAL_KNOWLEDGE_TEXT)
    METACOGNITIVE_KNOWLEDGE=(4,METACOGNITIVE_KNOWLEDGE_TEXT)

PER_LEVEL_GENERAL_RULES= USEFUL_DIMENSIONS_OF_BLOOMPERLEVEL_DIFFICULTY
class HardnessPerLevel(Enum):
    REMEMBER_DIFFICULTY=(1,REMEMBER_DIFFICULTY_TEXT)
    UNDERSTAND_DIFFICULTY=(2,UNDERSTAND_DIFFICULTY_TEXT)
    APPLY_DIFFICULTY=(3,APPLY_DIFFICULTY_TEXT)
    ANALYZE_DIFFICULTY=(4,ANALYZE_DIFFICULTY_TEXT)
    EVALUATE_DIFFICULTY=(5,EVALUATE_DIFFICULTY_TEXT)
    CREATE_DIFFICULTY=(6,CREATE_DIFFICULTY_TEXT)